bug#64034: [PATCH] libparted: link libparted-fs-resize.so to libuuid
uuid_generate() is used in this library
Hence, add UUID_LIBS to libparted_fs_resize_la_LIBADD to avoid

"ld.lld: error: undefined reference due to --no-allow-shlib-undefined: uuid_generate"

This is uncovered by lld linker linking fatresize package
due to this linker defaulting to --no-allow-shlib-undefined.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Brian C. Lane <bcl@redhat.com>