libparted: Leave device in read_only mode
Now that the device can be opened in read only mode on purpose, don't
set the read_only to 0 on success. If read_only happens because of an
actual problem with the device it's safer to leave it anyway, and this
makes parted return the proper error when trying a write operation:

  Error: Can't write to /root/disk.img, because it is opened read-only.