include/parted/unit.in.h: Specify const attribute to ped_unit_get_name()
GCC 8 fails to compile libparted/unit.c with an error:

  CC       unit.lo
unit.c:155:1: error: function might be candidate for attribute 'const' [-Werror=suggest-attribute=const]
 ped_unit_get_name (PedUnit unit)
 ^~~~~~~~~~~~~~~~~
  CC       disk.lo
cc1: all warnings being treated as errors

Const attribute is required for the function ped_unit_get_name() because
its return value is not affected by program status. To avoid the build
failure, change attribute of the function from pure to const.

Signed-off-by: Shin'ichiro Kawasaki <kawasaki@juno.dti.ne.jp>
Signed-off-by: Brian C. Lane <bcl@redhat.com>