ped_unit_get_name: Resolve conflicting attributes 'const' and 'pure'
The const and pure attributes conflict:

  error: ignoring attribute 'const' because it conflicts with attribute 'pure' [-Werror=attributes]

pure functions may access global memory, const functions may not.
ped_unit_get_name() accesses non-local variable unit_names, so drop const.

Signed-off-by: Brian C. Lane <bcl@redhat.com>